name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: KEXT

jobs:
  build:
    name: 使用Xcode13.0构建
    runs-on: macos-11
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: wy414012/MacKernelSDK
          path: MacKernelSDK
      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/wy414012/ocbuild/Yaming/ci-bootstrap.sh) && eval "$src" || exit 1
      - name: Lilu Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/wy414012/Lilu/yaming-network/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1

      - run: xcodebuild -jobs 1 -configuration Debug
      - run: xcodebuild -jobs 1 -configuration Release

      - name: 打包上传工作件
        uses: actions/upload-artifact@v2
        with:
          name: CpuTSync-build
          path: build/*/*.zip

 - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: build/*/*.zip
          asset_name: my-artifact.zip
          asset_content_type: application/zip


